name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    # Latest has issues with Cypress
    # https://github.com/cypress-io/github-action/issues/65#issuecomment-577603416
    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - uses: './'
