name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}

jobs:
  baseUrl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: './'
      with:
        appName: 'Colby Fayock Web'
        baseUrl: https://colbyfayock.com

  sitemapUrl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: './'
      with:
        appName: 'Next.js WordPress Starter'
        sitemapUrl: https://next-wordpress-starter.netlify.app/sitemap.xml

  concurrency:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: './'
      with:
        appName: 'Next.js WordPress Starter'
        sitemapUrl: https://next-wordpress-starter.netlify.app/sitemap.xml
        concurrency: 20